FROM andrewosh/binder-python-3.5-mini:latest

# Modified prefix from https://github.com/binder-project/binder-build-core/blob/master/lib/builder.js#L110
RUN mkdir /home/main/notebooks
RUN chown main:main /home/main/notebooks
WORKDIR /home/main/notebooks
USER root
COPY . /home/main/notebooks
RUN chown -R main:main $HOME/notebooks

USER main
RUN test -d $HOME/.jupyter || mkdir $HOME/.jupyter
RUN echo "c.NotebookApp.token = ''" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.password=''" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.iopub_data_rate_limit=1e22" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.password_required=False" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN find $HOME/notebooks -name '*.ipynb' -exec jupyter trust {} \;

# See https://github.com/aadm/avo_explorer/blob/master/Dockerfile
# Copy from the Dockerfile generated by binder to create and activate the conda environment
MAINTAINER Nezar Abdennur <nabdennur@gmail.com>

USER root

USER main
ADD environment.yml environment.yml
RUN conda env create -n binder
RUN echo "export PATH=$HOME/miniconda3/envs/binder/bin/:$PATH" >> ~/.binder_start
RUN conda install -n binder jupyter
RUN /bin/bash -c "source activate binder && jupyter kernelspec install-self --user"

# Suffix from https://github.com/binder-project/binder-build-core/blob/master/lib/builder.js#L110
USER main
RUN jupyter-notebook --ip 0.0.0.0
WORKDIR $HOME/notebooks
